# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df8a1e4a2f76646f472abe0b43c2278ae1e0f4c32856aa699979efa1fe85ac482244ba5211141444910f961cbd42967d474b59ca573fea5d8eb7fa83d1bfe22

test:
  secret_key_base: 83900134213c59b1e8466546b24ce4cab28e6f5c6fcd19abfd840cd28f9c3df6c5c2b6ef438a2287c7845b9ec8ba8aa4293e091b4d27dd450c07d4fe56b11114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
